import { FlipCard } from "@/components/flip-card";
import { ContactDetails } from "@/components/contact-details";
import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/ui";
import { CompanyLogo } from "@/components/brand";
import { ArrowUpRight } from "@/components/icons";
import { site } from "@/data/site";

const description = "Aviral Khanna's Razorpay work: merchant automation, AI triage, PGOS development and Coralogix monitoring. 306 automated data fixes, 98 ReKYC resets and approximately 93 hours saved.";
export const metadata: Metadata = {title:"Razorpay — Engineering Case Study",description,alternates:{canonical:"/razorpay"},openGraph:{title:"Aviral Khanna · Engineering at Razorpay",description,url:"/razorpay"},twitter:{card:"summary",title:"Aviral Khanna · Engineering at Razorpay",description}};
const metrics = [["306","automated data fixes"],["98","ReKYC resets"],["~93h","manual work saved"],["231","AI triage invocations"]];
const work = [
  {n:"01",title:"Merchant operations automation",tag:"Shell · REST APIs · State validation",body:"Built a six-script toolkit that reads live merchant state, selects the right update API, and validates changes before execution. Automated 306 data fixes and 98 ReKYC resets.",points:["Pre-flight checks block unsafe writes on activated merchants.","Dry-run previews, type inference, multi-field updates and 50+ field aliases.","Approximately 85% less time per datafix ticket; zero automation errors reported."]},
  {n:"02",title:"AI triage: merchant-pse",tag:"Claude · DevRev · Live API context",body:"Built an AI skill that runs when an R1/SME ticket is created, reads the issue, fetches live onboarding state, and returns a diagnosis, fix path or escalation.",points:["19 issue types and 32+ diagnosis patterns; approximately 90 seconds per run.","231 recorded invocations across 5+ channels; approximately ₹15 per run.","Scope detection, duplicate-issue checks and post-resolution quality validation."]},
  {n:"03",title:"PGOS & payment reliability",tag:"Production development · Root-cause fixes",body:"Contributed to PGOS production development and feature enhancements across critical payment flows. Turned recurring support issues into automation and root-cause fixes.",points:["Post Payments support volume reduced from 500+ to 40 tickets per month.","Contributed to India onboarding and infrastructure initiatives reducing volume from 2,000+ to approximately 1,000 tickets per month.","Worked across Payments, Routing, Orders, Webhooks, Refunds, Ledger, Subscriptions and Settlements."]},
  {n:"04",title:"AI monitoring with Coralogix",tag:"Observability · Log analysis · Alerting",body:"Built an internal AI bug-monitoring and alerting system integrated with Coralogix to turn high-volume production logs into actionable signals.",points:["Processed approximately 10 million logs per day.","Reduced response latency by approximately 40%.","Connected monitoring and alerting to day-to-day production troubleshooting."]},
];
const scripts = [["update.sh","Routes updates from live merchant state"],["pgos_datafix.sh","Applies validated, multi-field data fixes"],["onboarding_save.sh","Checks state before writing to unlocked workflows"],["rekyc_reset.sh","Resets ReKYC and sets a 30-day deadline"],["onboarding_get.sh","Reads progress, components and missing fields"],["run.sh","Normalizes 50+ aliases for repeatable fixes"]];
export default function RazorpayPage(){return <>
<section className="relative overflow-hidden border-b border-border"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,#3395ff20,transparent_65%)]"/><Container className="relative py-12 sm:py-16"><Link href="/" className="text-sm text-muted hover:text-foreground">← Aviral’s portfolio</Link><div className="mt-8 flex items-center gap-4"><CompanyLogo logo="razorpay" mark="R" brand="#3395FF" size="lg"/><div><p className="font-mono text-sm uppercase tracking-wider text-[#3395ff]">Engineering at Razorpay</p><p className="mt-1 text-sm text-muted">Intern, Product Support Engineering · R1/SME</p></div></div><h1 className="mt-7 max-w-3xl font-display text-4xl tracking-tight sm:text-6xl">Payments. Automation.<br/>Less repetitive work.</h1><p className="mt-5 max-w-2xl text-lg leading-relaxed text-muted">I built tools for merchant operations, AI triage and production monitoring, alongside development work on PGOS payment flows.</p><p className="mt-4 text-sm text-muted">Aviral Khanna · 15 September 2025 – 30 June 2026</p><div className="mt-9 grid grid-cols-2 gap-px overflow-hidden rounded-2xl border border-border bg-border sm:grid-cols-4">{metrics.map(([n,l])=><div key={l} className="bg-surface px-5 py-6"><p className="font-mono text-3xl font-semibold tracking-tight text-[#3395ff]">{n}</p><p className="mt-2 text-sm text-muted">{l}</p></div>)}</div><nav aria-label="Case study sections" className="mt-7 flex flex-wrap gap-x-6 gap-y-3 text-sm"><a href="#work" className="hover:text-accent">What I built ↓</a><a href="#architecture" className="hover:text-accent">How it works ↓</a><a href="#results" className="hover:text-accent">Results & adoption ↓</a></nav></Container></section>
<Container className="py-12 sm:py-16"><section id="work" className="scroll-mt-24"><p className="font-mono text-xs uppercase tracking-widest text-muted">Four areas of work</p><h2 className="mt-3 font-display text-3xl tracking-tight">From support patterns to production tools.</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{work.map(w=><FlipCard key={w.n} title={w.title} eyebrow={`Razorpay · ${w.n}`}> <p className="mt-2 text-xs font-medium text-[#3395ff]">{w.tag}</p><p className="mt-5 text-base leading-relaxed text-muted">{w.body}</p><ul className="mt-4 space-y-3">{w.points.map(p=><li key={p} className="flex gap-3 text-sm leading-relaxed text-muted"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#3395ff]"/>{p}</li>)}</ul></FlipCard>)}</div></section>
<section id="architecture" className="mt-14 scroll-mt-24"><h2 className="font-display text-3xl tracking-tight">The right API for the merchant’s state.</h2><p className="mt-3 max-w-2xl text-muted">A small, repeatable workflow connects diagnosis to a safe update. State is read again after the change to verify the result.</p><ol className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["01","Receive & validate","Ticket or merchant ID; normalize fields and values."],["02","Read live state","Fetch onboarding status and pending components."],["03","Route & execute","Choose the appropriate API; apply safety checks."],["04","Verify & record","Read back the updated state and retain an audit trail."]].map(([n,t,d])=><li key={n}><FlipCard title={t} eyebrow={`Step ${n}`}><p className="text-sm leading-relaxed text-muted">{d}</p></FlipCard></li>)}</ol><div className="mt-4 grid gap-4 sm:grid-cols-2"><p className="rounded-xl bg-surface-2 p-4 text-sm leading-relaxed"><strong>Unlocked workflow:</strong> <span className="text-muted">OnboardingSave, after pre-flight checks.</span></p><p className="rounded-xl bg-surface-2 p-4 text-sm leading-relaxed"><strong>Submitted / locked fields:</strong> <span className="text-muted">pseDatafix, followed by read-back verification.</span></p></div><details className="mt-5 rounded-xl border border-border bg-surface p-5"><summary className="cursor-pointer font-medium">The six-script toolkit</summary><dl className="mt-5 grid gap-4 sm:grid-cols-2">{scripts.map(([n,d])=><div key={n}><dt className="font-mono text-sm text-[#3395ff]">{n}</dt><dd className="mt-1 text-sm text-muted">{d}</dd></div>)}</dl></details></section>
<section id="results" className="mt-14 scroll-mt-24"><h2 className="font-display text-3xl tracking-tight">Measured impact. Wider adoption.</h2><div className="mt-7 grid gap-5 md:grid-cols-2"><FlipCard title="Onboarding work report" eyebrow="Results"><dl className="mt-5 grid grid-cols-2 gap-5">{[["420","tickets owned"],["280","solo resolutions"],["92.1%","SLA hit rate"],["16h","median resolution"]].map(([n,l])=><div key={l}><dt className="font-mono text-2xl text-[#3395ff]">{n}</dt><dd className="mt-1 text-sm text-muted">{l}</dd></div>)}</dl><p className="mt-6 text-sm leading-relaxed text-muted">327 total data fixes: 306 automated PSE fixes and 21 developer fixes. 194 tickets resolved within eight hours; 53 escalated to development. SLA was approximately 7.1 percentage points above the team average, with team rank #3.</p><p className="mt-4 text-sm leading-relaxed text-muted">Reported savings: 76.5 hours from datafixes and 16.3 from ReKYC resets — approximately 93 hours combined.</p></FlipCard><FlipCard title="A repeatable AI triage pattern" eyebrow="Adoption"><ol className="mt-5 space-y-5"><li><p className="font-mono text-xs text-[#3395ff]">4 MAY 2026</p><p className="mt-1 text-sm leading-relaxed text-muted">merchant-pse shipped as the first R1/SME PSE skill.</p></li><li><p className="font-mono text-xs text-[#3395ff]">14 MAY 2026</p><p className="mt-1 text-sm leading-relaxed text-muted">Four more pod skills followed: Ledger, Route, VAS and Reporting Support.</p></li><li><p className="font-mono text-xs text-[#3395ff]">231 INVOCATIONS · 5+ CHANNELS</p><p className="mt-1 text-sm leading-relaxed text-muted">Used beyond the R1 pod for on-call triage and cross-team debugging.</p></li></ol><p className="mt-5 text-sm leading-relaxed text-muted">Post-resolution checks cover 40+ pod-routing rules and 50+ cause codes, keeping tags and resolution data consistent.</p></FlipCard></div><p className="mt-5 text-xs leading-relaxed text-muted">Figures are from my work report and experience records. Approximate savings and runtime remain estimates. Post Payments, onboarding and Coralogix metrics describe separate initiatives.</p></section>
<div className="mt-12 flex flex-wrap items-center justify-between gap-5 border-t border-border pt-8"><div><h2 className="font-display text-2xl">Get in touch</h2><p className="mt-2 text-muted">Want to discuss the engineering behind this work?</p><ContactDetails /></div><a href={site.socials.email} className="inline-flex items-center gap-2 rounded-full bg-accent px-5 py-3 text-sm font-medium text-accent-foreground">Get in touch <ArrowUpRight width={16} height={16}/></a></div></Container></>}
